const fs = require('fs');
const path = require('path');

const A1_PATH = path.join(__dirname, '../server/data/sentences.a1.json');
const A2_PATH = path.join(__dirname, '../server/data/sentences.a2.json');

const a1Data = JSON.parse(fs.readFileSync(A1_PATH, 'utf8'));
const a2Data = JSON.parse(fs.readFileSync(A2_PATH, 'utf8'));

// High quality vocabulary map for the curriculum words
const VOCAB_MAP = {
  about: { tr: 'عن / تقريبًا', pos: 'preposition', pr: '/əˈbaʊt/' },
  accept: { tr: 'يقبل', pos: 'verb', pr: '/əkˈsɛpt/' },
  account: { tr: 'حساب', pos: 'noun', pr: '/əˈkaʊnt/' },
  address: { tr: 'عنوان', pos: 'noun', pr: '/əˈdrɛs/' },
  afraid: { tr: 'خائف', pos: 'adjective', pr: '/əˈfreɪd/' },
  agree: { tr: 'يوافق', pos: 'verb', pr: '/əˈɡriː/' },
  ahead: { tr: 'إلى الأمام / مسبقًا', pos: 'adverb', pr: '/əˈhɛd/' },
  ahmed: { tr: 'أحمد', pos: 'noun', pr: '/ˈɑːxmɛd/' },
  air: { tr: 'هواء', pos: 'noun', pr: '/ɛər/' },
  allergic: { tr: 'لديه حساسية', pos: 'adjective', pr: '/əˈlɜːrdʒɪk/' },
  almost: { tr: 'تقريبًا', pos: 'adverb', pr: '/ˈɔːlmoʊst/' },
  ambulance: { tr: 'سيارة إسعاف', pos: 'noun', pr: '/ˈæmbjələns/' },
  angry: { tr: 'غاضب', pos: 'adjective', pr: '/ˈæŋɡri/' },
  another: { tr: 'آخر', pos: 'determiner', pr: '/əˈnʌðər/' },
  any: { tr: 'أي', pos: 'determiner', pr: '/ˈɛni/' },
  anyone: { tr: 'أي شخص', pos: 'pronoun', pr: '/ˈɛniwʌn/' },
  anything: { tr: 'أي شيء', pos: 'pronoun', pr: '/ˈɛniθɪŋ/' },
  app: { tr: 'تطبيق', pos: 'noun', pr: '/æp/' },
  appointment: { tr: 'موعد', pos: 'noun', pr: '/əˈpɔɪntmənt/' },
  around: { tr: 'حوالي / حول', pos: 'preposition', pr: '/əˈraʊnd/' },
  arrived: { tr: 'وصل', pos: 'verb', pr: '/əˈraɪvd/' },
  artificial: { tr: 'اصطناعي', pos: 'adjective', pr: '/ˌɑːrtɪˈfɪʃəl/' },
  asking: { tr: 'يسأل / يطلب', pos: 'verb', pr: '/ˈæskɪŋ/' },
  attach: { tr: 'يرفق', pos: 'verb', pr: '/əˈtætʃ/' },
  available: { tr: 'متاح', pos: 'adjective', pr: '/əˈveɪləbəl/' },
  away: { tr: 'بعيدًا', pos: 'adverb', pr: '/əˈweɪ/' },
  baggage: { tr: 'أمتعة', pos: 'noun', pr: '/ˈbæɡɪdʒ/' },
  battery: { tr: 'بطارية', pos: 'noun', pr: '/ˈbætəri/' },
  be: { tr: 'يكون', pos: 'verb', pr: '/biː/' },
  been: { tr: 'كان (تصريف ثالث)', pos: 'verb', pr: '/bɪn/' },
  big: { tr: 'كبير', pos: 'adjective', pr: '/bɪɡ/' },
  bill: { tr: 'فاتورة', pos: 'noun', pr: '/bɪl/' },
  birthday: { tr: 'عيد ميلاد', pos: 'noun', pr: '/ˈbɜːrθdeɪ/' },
  black: { tr: 'أسود', pos: 'adjective', pr: '/blæk/' },
  bottle: { tr: 'زجاجة', pos: 'noun', pr: '/ˈbɒtəl/' },
  bought: { tr: 'اشترى', pos: 'verb', pr: '/bɔːt/' },
  breath: { tr: 'نَفَس', pos: 'noun', pr: '/brɛθ/' },
  breathe: { tr: 'يتنفس', pos: 'verb', pr: '/briːð/' },
  bug: { tr: 'خطأ برمجي', pos: 'noun', pr: '/bʌɡ/' },
  button: { tr: 'زر', pos: 'noun', pr: '/ˈbʌtən/' },
  by: { tr: 'بواسطة / بحلول', pos: 'preposition', pr: '/baɪ/' },
  came: { tr: 'جاء / أتى', pos: 'verb', pr: '/keɪm/' },
  canceled: { tr: 'ملغى', pos: 'adjective', pr: '/ˈkænsəld/' },
  cannot: { tr: 'لا يستطيع', pos: 'verb', pr: '/ˈkænɒt/' },
  cards: { tr: 'بطاقات', pos: 'noun', pr: '/kɑːrdz/' },
  care: { tr: 'يعتني / عناية', pos: 'verb', pr: '/kɛər/' },
  change: { tr: 'يغيّر / فكة', pos: 'verb', pr: '/tʃeɪndʒ/' },
  cheaper: { tr: 'أرخص', pos: 'adjective', pr: '/ˈtʃiːpər/' },
  chicken: { tr: 'دجاج', pos: 'noun', pr: '/ˈtʃɪkɪn/' },
  choice: { tr: 'خيار', pos: 'noun', pr: '/tʃɔɪs/' },
  claim: { tr: 'مطالبة / استلام', pos: 'noun', pr: '/kleɪm/' },
  click: { tr: 'ينقر', pos: 'verb', pr: '/klɪk/' },
  clinic: { tr: 'عيادة', pos: 'noun', pr: '/ˈklɪnɪk/' },
  closed: { tr: 'مغلق', pos: 'adjective', pr: '/kloʊzd/' },
  code: { tr: 'كود / شفرة', pos: 'noun', pr: '/koʊd/' },
  come: { tr: 'يأتي', pos: 'verb', pr: '/kʌm/' },
  comfortable: { tr: 'مريح', pos: 'adjective', pr: '/ˈkʌmftərbəl/' },
  complete: { tr: 'يكتمل / كامل', pos: 'adjective', pr: '/kəmˈpliːt/' },
  completely: { tr: 'تمامًا', pos: 'adverb', pr: '/kəmˈpliːtli/' },
  computer: { tr: 'حاسوب', pos: 'noun', pr: '/kəmˈpjuːtər/' },
  confused: { tr: 'مرتبك', pos: 'adjective', pr: '/kənˈfjuːzd/' },
  connect: { tr: 'يتصل', pos: 'verb', pr: '/kəˈnɛkt/' },
  connection: { tr: 'اتصال', pos: 'noun', pr: '/kəˈnɛkʃən/' },
  control: { tr: 'تحكم / يسيطر', pos: 'noun', pr: '/kənˈtroʊl/' },
  correct: { tr: 'صحيح', pos: 'adjective', pr: '/kəˈrɛkt/' },
  could: { tr: 'استطاع / يمكن', pos: 'verb', pr: '/kʊd/' },
  create: { tr: 'ينشئ / يخلق', pos: 'verb', pr: '/kriˈeɪt/' },
  credit: { tr: 'ائتمان', pos: 'noun', pr: '/ˈkrɛdɪt/' },
  dangerous: { tr: 'خطير', pos: 'adjective', pr: '/ˈdeɪndʒərəs/' },
  dead: { tr: 'ميت / فارغ الشحن', pos: 'adjective', pr: '/dɛd/' },
  deadline: { tr: 'الموعد النهائي', pos: 'noun', pr: '/ˈdɛdlaɪn/' },
  deal: { tr: 'صفقة / يتعامل', pos: 'noun', pr: '/diːl/' },
  decide: { tr: 'يقرر', pos: 'verb', pr: '/dɪˈsaɪd/' },
  deep: { tr: 'عميق', pos: 'adjective', pr: '/diːp/' },
  delayed: { tr: 'متأخر', pos: 'adjective', pr: '/dɪˈleɪd/' },
  departure: { tr: 'المغادرة', pos: 'noun', pr: '/dɪˈpɑːrtʃər/' },
  depends: { tr: 'يعتمد', pos: 'verb', pr: '/dɪˈpɛndz/' },
  details: { tr: 'تفاصيل', pos: 'noun', pr: '/ˈdiːteɪlz/' },
  did: { tr: 'فعل (ماضي)', pos: 'verb', pr: '/dɪd/' },
  difficult: { tr: 'صعب', pos: 'adjective', pr: '/ˈdɪfɪkəlt/' },
  directions: { tr: 'اتجاهات', pos: 'noun', pr: '/dɪˈrɛkʃənz/' },
  disappointed: { tr: 'خائب الأمل', pos: 'adjective', pr: '/ˌdɪsəˈpɔɪntɪd/' },
  discount: { tr: 'خصم', pos: 'noun', pr: '/ˈdɪskaʊnt/' },
  distance: { tr: 'مسافة', pos: 'noun', pr: '/ˈdɪstəns/' },
  dizzy: { tr: 'يشعر بالدوار', pos: 'adjective', pr: '/ˈdɪzi/' },
  doing: { tr: 'يفعل / حاله', pos: 'verb', pr: '/ˈduːɪŋ/' },
  done: { tr: 'تم / منتهي', pos: 'adjective', pr: '/dʌn/' },
  down: { tr: 'أسفل / معطل', pos: 'adverb', pr: '/daʊn/' },
  download: { tr: 'تحميل', pos: 'verb', pr: '/ˈdaʊnloʊd/' },
  dressed: { tr: 'يرتدي ملابسه', pos: 'adjective', pr: '/drɛst/' },
  egypt: { tr: 'مصر', pos: 'noun', pr: '/ˈiːdʒɪpt/' },
  eleven: { tr: 'أحد عشر', pos: 'number', pr: '/ɪˈlɛvən/' },
  email: { tr: 'بريد إلكتروني', pos: 'noun', pr: '/ˈiːmeɪl/' },
  enjoy: { tr: 'يستمتع', pos: 'verb', pr: '/ɪnˈdʒɔɪ/' },
  enough: { tr: 'كافٍ', pos: 'adjective', pr: '/ɪˈnʌf/' },
  everything: { tr: 'كل شيء', pos: 'pronoun', pr: '/ˈɛvriθɪŋ/' },
  exactly: { tr: 'بالضبط', pos: 'adverb', pr: '/ɪɡˈzæktli/' },
  excited: { tr: 'متحمس', pos: 'adjective', pr: '/ɪkˈsaɪtɪd/' },
  excuse: { tr: 'عذرًا / يعذر', pos: 'verb', pr: '/ɪkˈskjuːz/' },
  explain: { tr: 'يشرح', pos: 'verb', pr: '/ɪkˈspleɪn/' },
  explaining: { tr: 'شرح / يوضح', pos: 'verb', pr: '/ɪkˈspleɪnɪŋ/' },
  extra: { tr: 'إضافي', pos: 'adjective', pr: '/ˈɛkstrə/' },
  fare: { tr: 'أجرة', pos: 'noun', pr: '/fɛər/' },
  favor: { tr: 'معروف / خدمة', pos: 'noun', pr: '/ˈfeɪvər/' },
  feeling: { tr: 'شعور / يشعر', pos: 'verb', pr: '/ˈfiːlɪŋ/' },
  fi: { tr: 'فاي (واي فاي)', pos: 'noun', pr: '/faɪ/' },
  file: { tr: 'ملف', pos: 'noun', pr: '/faɪl/' },
  files: { tr: 'ملفات', pos: 'noun', pr: '/faɪlz/' },
  fine: { tr: 'بخير', pos: 'adjective', pr: '/faɪn/' },
  finished: { tr: 'انتهى', pos: 'verb', pr: '/ˈfɪnɪʃt/' },
  first: { tr: 'أولاً / الأول', pos: 'adjective', pr: '/fɜːrst/' },
  fitting: { tr: 'قياس (غرفة القياس)', pos: 'noun', pr: '/ˈfɪtɪŋ/' },
  fixed: { tr: 'تم إصلاحه', pos: 'verb', pr: '/fɪkst/' },
  flight: { tr: 'رحلة طيران', pos: 'noun', pr: '/flaɪt/' },
  focus: { tr: 'يركز / تركيز', pos: 'verb', pr: '/ˈfoʊkəs/' },
  follow: { tr: 'يتبع', pos: 'verb', pr: '/ˈfɒloʊ/' },
  foot: { tr: 'قدم', pos: 'noun', pr: '/fʊt/' },
  forget: { tr: 'ينسى', pos: 'verb', pr: '/fərˈɡɛt/' },
  forgot: { tr: 'نسي', pos: 'verb', pr: '/fərˈɡɒt/' },
  found: { tr: 'وجد', pos: 'verb', pr: '/faʊnd/' },
  free: { tr: 'حر / متفرغ / مجاني', pos: 'adjective', pr: '/friː/' },
  friend: { tr: 'صديق', pos: 'noun', pr: '/frɛnd/' },
  frozen: { tr: 'متجمد / معلق', pos: 'adjective', pr: '/ˈfroʊzən/' },
  gate: { tr: 'بوابة', pos: 'noun', pr: '/ɡeɪt/' },
  get: { tr: 'يحصل على / يصل', pos: 'verb', pr: '/ɡɛt/' },
  give: { tr: 'يعطي', pos: 'verb', pr: '/ɡɪv/' },
  glad: { tr: 'مسرور', pos: 'adjective', pr: '/ɡlæd/' },
  going: { tr: 'ذاهب', pos: 'verb', pr: '/ˈɡoʊɪŋ/' },
  got: { tr: 'حصل على', pos: 'verb', pr: '/ɡɒt/' },
  great: { tr: 'عظيم / رائع', pos: 'adjective', pr: '/ɡreɪt/' },
  had: { tr: 'كان لديه', pos: 'verb', pr: '/hæd/' },
  happened: { tr: 'حدث', pos: 'verb', pr: '/ˈhæpənd/' },
  hate: { tr: 'يكره', pos: 'verb', pr: '/heɪt/' },
  hear: { tr: 'يسمع', pos: 'verb', pr: '/hɪər/' },
  heights: { tr: 'مرتفعات', pos: 'noun', pr: '/haɪts/' },
  help: { tr: 'يساعد / مساعدة', pos: 'verb', pr: '/hɛlp/' },
  helping: { tr: 'مساعدة', pos: 'verb', pr: '/ˈhɛlpɪŋ/' },
  hi: { tr: 'مرحبًا', pos: 'interjection', pr: '/haɪ/' },
  hold: { tr: 'يمسك / ينتظر', pos: 'verb', pr: '/hoʊld/' },
  honest: { tr: 'صادق', pos: 'adjective', pr: '/ˈɒnɪst/' },
  hope: { tr: 'يأمل', pos: 'verb', pr: '/hoʊp/' },
  hospital: { tr: 'مستشفى', pos: 'noun', pr: '/ˈhɒspɪtəl/' },
  idea: { tr: 'فكرة', pos: 'noun', pr: '/aɪˈdɪə/' },
  impossible: { tr: 'مستحيل', pos: 'adjective', pr: '/ɪmˈpɒsəbəl/' },
  improve: { tr: 'يتحسن / يطوّر', pos: 'verb', pr: '/ɪmˈpruːv/' },
  inbox: { tr: 'صندوق الوارد', pos: 'noun', pr: '/ˈɪnbɒks/' },
  included: { tr: 'مشمول / متضمن', pos: 'adjective', pr: '/ɪnˈkluːdɪd/' },
  incorrect: { tr: 'غير صحيح', pos: 'adjective', pr: '/ˌɪnkəˈrɛkt/' },
  intelligence: { tr: 'ذكاء', pos: 'noun', pr: '/ɪnˈtɛlɪdʒəns/' },
  internet: { tr: 'إنترنت', pos: 'noun', pr: '/ˈɪntərnɛt/' },
  interview: { tr: 'مقابلة', pos: 'noun', pr: '/ˈɪntərvjuː/' },
  introduce: { tr: 'يقدم', pos: 'verb', pr: '/ˌɪntrəˈdjuːs/' },
  join: { tr: 'ينضم', pos: 'verb', pr: '/dʒɔɪn/' },
  just: { tr: 'فقط / للتو', pos: 'adverb', pr: '/dʒʌst/' },
  keys: { tr: 'مفاتيح', pos: 'noun', pr: '/kiːz/' },
  kidding: { tr: 'يمزح', pos: 'verb', pr: '/ˈkɪdɪŋ/' },
  know: { tr: 'يعرف', pos: 'verb', pr: '/noʊ/' },
  large: { tr: 'كبير', pos: 'adjective', pr: '/lɑːrdʒ/' },
  late: { tr: 'متأخر', pos: 'adjective', pr: '/leɪt/' },
  later: { tr: 'لاحقًا', pos: 'adverb', pr: '/ˈleɪtər/' },
  laundry: { tr: 'غسيل الملابس', pos: 'noun', pr: '/ˈlɔːndri/' },
  learning: { tr: 'تعلّم', pos: 'noun', pr: '/ˈlɜːrnɪŋ/' },
  leave: { tr: 'يغادر', pos: 'verb', pr: '/liːv/' },
  lecture: { tr: 'محاضرة', pos: 'noun', pr: '/ˈlɛktʃər/' },
  left: { tr: 'يسار / غادر', pos: 'adjective', pr: '/lɛft/' },
  less: { tr: 'أقل', pos: 'adverb', pr: '/lɛs/' },
  let: { tr: 'يدع / يسمح', pos: 'verb', pr: '/lɛt/' },
  light: { tr: 'خفيف / ضوء', pos: 'adjective', pr: '/laɪt/' },
  link: { tr: 'رابط', pos: 'noun', pr: '/lɪŋk/' },
  listen: { tr: 'يستمع', pos: 'verb', pr: '/ˈlɪsən/' },
  loading: { tr: 'يحمّل', pos: 'verb', pr: '/ˈloʊdɪŋ/' },
  locked: { tr: 'مقفل', pos: 'adjective', pr: '/lɒkt/' },
  log: { tr: 'تسجيل دخول', pos: 'verb', pr: '/lɒɡ/' },
  long: { tr: 'طويل', pos: 'adjective', pr: '/lɒŋ/' },
  looking: { tr: 'يبحث / ينظر', pos: 'verb', pr: '/ˈlʊkɪŋ/' },
  lost: { tr: 'مفقود / ضائع', pos: 'adjective', pr: '/lɒst/' },
  lot: { tr: 'كثير', pos: 'noun', pr: '/lɒt/' },
  low: { tr: 'منخفض', pos: 'adjective', pr: '/loʊ/' },
  luck: { tr: 'حظ', pos: 'noun', pr: '/lʌk/' },
  luggage: { tr: 'أمتعة', pos: 'noun', pr: '/ˈlʌɡɪdʒ/' },
  made: { tr: 'صنع / فعل', pos: 'verb', pr: '/meɪd/' },
  make: { tr: 'يصنع / يجعل', pos: 'verb', pr: '/meɪk/' },
  makes: { tr: 'يجعل', pos: 'verb', pr: '/meɪks/' },
  matter: { tr: 'يهم / أمر', pos: 'verb', pr: '/ˈmætər/' },
  meat: { tr: 'لحم', pos: 'noun', pr: '/miːt/' },
  menu: { tr: 'قائمة الطعام', pos: 'noun', pr: '/ˈmɛnjuː/' },
  might: { tr: 'قد / ربما', pos: 'verb', pr: '/maɪt/' },
  mind: { tr: 'يمانع / عقل', pos: 'verb', pr: '/maɪnd/' },
  minute: { tr: 'دقيقة', pos: 'noun', pr: '/ˈmɪnɪt/' },
  miss: { tr: 'يفوت / يشتاق', pos: 'verb', pr: '/mɪs/' },
  missed: { tr: 'فاتني', pos: 'verb', pr: '/mɪst/' },
  missing: { tr: 'مفقود', pos: 'adjective', pr: '/ˈmɪsɪŋ/' },
  moment: { tr: 'لحظة', pos: 'noun', pr: '/ˈmoʊmənt/' },
  mood: { tr: 'مزاج', pos: 'noun', pr: '/muːd/' },
  move: { tr: 'يتحرك / ينتقل', pos: 'verb', pr: '/muːv/' },
  music: { tr: 'موسيقى', pos: 'noun', pr: '/ˈmjuːzɪk/' },
  myself: { tr: 'نفسي', pos: 'pronoun', pr: '/maɪˈsɛlf/' },
  nearby: { tr: 'قريب', pos: 'adjective', pr: '/ˌnɪərˈbaɪ/' },
  needed: { tr: 'احتاج', pos: 'verb', pr: '/ˈniːdɪd/' },
  needs: { tr: 'يحتاج', pos: 'verb', pr: '/niːdz/' },
  nervous: { tr: 'متوتر', pos: 'adjective', pr: '/ˈnɜːrvəs/' },
  network: { tr: 'شبكة', pos: 'noun', pr: '/ˈnɛtwɜːrk/' },
  never: { tr: 'أبدًا', pos: 'adverb', pr: '/ˈnɛvər/' },
  nothing: { tr: 'لا شيء', pos: 'pronoun', pr: '/ˈnʌθɪŋ/' },
  nour: { tr: 'نور', pos: 'noun', pr: '/nuːr/' },
  number: { tr: 'رقم', pos: 'noun', pr: '/ˈnʌmbər/' },
  nuts: { tr: 'مكسرات', pos: 'noun', pr: '/nʌts/' },
  of: { tr: 'من / لـ', pos: 'preposition', pr: '/əv/' },
  off: { tr: 'مغلق / مطفأ', pos: 'adverb', pr: '/ɒf/' },
  often: { tr: 'غالبًا', pos: 'adverb', pr: '/ˈɒfən/' },
  okay: { tr: 'حسنًا', pos: 'adjective', pr: '/oʊˈkeɪ/' },
  onions: { tr: 'بصل', pos: 'noun', pr: '/ˈʌnjənz/' },
  online: { tr: 'عبر الإنترنت', pos: 'adverb', pr: '/ˈɒnlaɪn/' },
  opinion: { tr: 'رأي', pos: 'noun', pr: '/əˈpɪnjən/' },
  order: { tr: 'طلب / يطلب', pos: 'noun', pr: '/ˈɔːrdər/' },
  out: { tr: 'خارج', pos: 'adverb', pr: '/aʊt/' },
  pack: { tr: 'يحزم الأمتعة', pos: 'verb', pr: '/pæk/' },
  page: { tr: 'صفحة', pos: 'noun', pr: '/peɪdʒ/' },
  passport: { tr: 'جواز سفر', pos: 'noun', pr: '/ˈpæspɔːrt/' },
  password: { tr: 'كلمة مرور', pos: 'noun', pr: '/ˈpæswɜːrd/' },
  pharmacy: { tr: 'صيدلية', pos: 'noun', pr: '/ˈfɑːrməsi/' },
  plan: { tr: 'خطة', pos: 'noun', pr: '/plæn/' },
  plans: { tr: 'خطط', pos: 'noun', pr: '/plænz/' },
  platform: { tr: 'رصيف محطة / منصة', pos: 'noun', pr: '/ˈplætfɔːrm/' },
  plenty: { tr: 'وفير / كافي', pos: 'noun', pr: '/ˈplɛnti/' },
  police: { tr: 'شرطة', pos: 'noun', pr: '/pəˈliːs/' },
  positive: { tr: 'إيجابي / متأكد', pos: 'adjective', pr: '/ˈpɒzətɪv/' },
  possible: { tr: 'ممكن', pos: 'adjective', pr: '/ˈpɒsəbəl/' },
  prefer: { tr: 'يفضل', pos: 'verb', pr: '/prɪˈfɜːr/' },
  preparing: { tr: 'يستعد / يجهّز', pos: 'verb', pr: '/prɪˈpɛərɪŋ/' },
  prescription: { tr: 'وصفة طبية', pos: 'noun', pr: '/prɪˈskrɪpʃən/' },
  presentation: { tr: 'عرض تقديمي', pos: 'noun', pr: '/ˌprɛzənˈteɪʃən/' },
  price: { tr: 'سعر', pos: 'noun', pr: '/praɪs/' },
  product: { tr: 'منتج', pos: 'noun', pr: '/ˈprɒdʌkt/' },
  programming: { tr: 'برمجة', pos: 'noun', pr: '/ˈproʊɡræmɪŋ/' },
  project: { tr: 'مشروع', pos: 'noun', pr: '/ˈprɒdʒɛkt/' },
  proud: { tr: 'فخور', pos: 'adjective', pr: '/praʊd/' },
  quickly: { tr: 'بسرعة', pos: 'adverb', pr: '/ˈkwɪkli/' },
  rarely: { tr: 'نادرًا', pos: 'adverb', pr: '/ˈrɛərli/' },
  rather: { tr: 'بدلاً من / إلى حد ما', pos: 'adverb', pr: '/ˈræðər/' },
  reasonable: { tr: 'معقول', pos: 'adjective', pr: '/ˈriːzənəbəl/' },
  receipt: { tr: 'إيصال', pos: 'noun', pr: '/rɪˈsiːt/' },
  receive: { tr: 'يستلم', pos: 'verb', pr: '/rɪˈsiːv/' },
  recommend: { tr: 'يوصي', pos: 'verb', pr: '/ˌrɛkəˈmɛnd/' },
  relax: { tr: 'يسترخي', pos: 'verb', pr: '/rɪˈlæks/' },
  remember: { tr: 'يتذكر', pos: 'verb', pr: '/rɪˈmɛmbər/' },
  reply: { tr: 'يرد', pos: 'verb', pr: '/rɪˈplaɪ/' },
  report: { tr: 'تقرير', pos: 'noun', pr: '/rɪˈpɔːrt/' },
  reschedule: { tr: 'يعيد جدولة', pos: 'verb', pr: '/ˌriːˈskɛdʒuːl/' },
  reservation: { tr: 'حجز', pos: 'noun', pr: '/ˌrɛzərˈveɪʃən/' },
  reserved: { tr: 'محجوز', pos: 'adjective', pr: '/rɪˈzɜːrvd/' },
  reset: { tr: 'إعادة تعيين', pos: 'verb', pr: '/riːˈsɛt/' },
  restart: { tr: 'إعادة تشغيل', pos: 'verb', pr: '/riːˈstɑːrt/' },
  result: { tr: 'نتيجة', pos: 'noun', pr: '/rɪˈzʌlt/' },
  review: { tr: 'مراجعة', pos: 'verb', pr: '/rɪˈvjuː/' },
  right: { tr: 'يمين / صحيح / الآن', pos: 'adverb', pr: '/raɪt/' },
  road: { tr: 'طريق', pos: 'noun', pr: '/roʊd/' },
  round: { tr: 'ذهاب وإياب / دائري', pos: 'adjective', pr: '/raʊnd/' },
  running: { tr: 'يعمل / يركض', pos: 'verb', pr: '/ˈrʌnɪŋ/' },
  rush: { tr: 'عجلة / اندفاع', pos: 'noun', pr: '/rʌʃ/' },
  safe: { tr: 'آمن', pos: 'adjective', pr: '/seɪf/' },
  salty: { tr: 'مالح', pos: 'adjective', pr: '/ˈsɔːlti/' },
  same: { tr: 'نفسه', pos: 'adjective', pr: '/seɪm/' },
  sandwich: { tr: 'شطيرة', pos: 'noun', pr: '/ˈsænwɪtʃ/' },
  save: { tr: 'يحفظ', pos: 'verb', pr: '/seɪv/' },
  screen: { tr: 'شاشة', pos: 'noun', pr: '/skriːn/' },
  screenshot: { tr: 'لقطة شاشة', pos: 'noun', pr: '/ˈskriːnʃɒt/' },
  seat: { tr: 'مقعد', pos: 'noun', pr: '/siːt/' },
  second: { tr: 'ثانية / ثانٍ', pos: 'noun', pr: '/ˈsɛkənd/' },
  sense: { tr: 'منطق / معنى', pos: 'noun', pr: '/sɛns/' },
  sent: { tr: 'أرسل', pos: 'verb', pr: '/sɛnt/' },
  serious: { tr: 'جاد / خطير', pos: 'adjective', pr: '/ˈsɪəriəs/' },
  server: { tr: 'خادم', pos: 'noun', pr: '/ˈsɜːrvər/' },
  shopping: { tr: 'تسوق', pos: 'noun', pr: '/ˈʃɒpɪŋ/' },
  should: { tr: 'ينبغي', pos: 'verb', pr: '/ʃʊd/' },
  show: { tr: 'يوضح / يظهر', pos: 'verb', pr: '/ʃoʊ/' },
  sick: { tr: 'مريض', pos: 'adjective', pr: '/sɪk/' },
  sit: { tr: 'يجلس', pos: 'verb', pr: '/sɪt/' },
  situation: { tr: 'موقف / وضع', pos: 'noun', pr: '/ˌsɪtʃuˈeɪʃən/' },
  size: { tr: 'مقاس / حجم', pos: 'noun', pr: '/saɪz/' },
  skills: { tr: 'مهارات', pos: 'noun', pr: '/skɪlz/' },
  skip: { tr: 'يتخطى', pos: 'verb', pr: '/skɪp/' },
  slow: { tr: 'بطيء', pos: 'adjective', pr: '/sloʊ/' },
  small: { tr: 'صغير', pos: 'adjective', pr: '/smɔːl/' },
  so: { tr: 'لذلك / جدًا', pos: 'adverb', pr: '/soʊ/' },
  someone: { tr: 'شخص ما', pos: 'pronoun', pr: '/ˈsʌmwʌn/' },
  something: { tr: 'شيء ما', pos: 'pronoun', pr: '/ˈsʌmθɪŋ/' },
  sometimes: { tr: 'أحيانًا', pos: 'adverb', pr: '/ˈsʌmtaɪmz/' },
  soon: { tr: 'قريبًا', pos: 'adverb', pr: '/suːn/' },
  sore: { tr: 'متقرح / مؤلم', pos: 'adjective', pr: '/sɔːr/' },
  sounds: { tr: 'يبدو', pos: 'verb', pr: '/saʊndz/' },
  spicy: { tr: 'حار', pos: 'adjective', pr: '/ˈspaɪsi/' },
  stable: { tr: 'مستقر', pos: 'adjective', pr: '/ˈsteɪbəl/' },
  still: { tr: 'ما زال', pos: 'adverb', pr: '/stɪl/' },
  stop: { tr: 'يتوقف / محطة', pos: 'verb', pr: '/stɒp/' },
  storage: { tr: 'مساحة تخزين', pos: 'noun', pr: '/ˈstɔːrɪdʒ/' },
  straight: { tr: 'مباشرة / إلى الأمام', pos: 'adverb', pr: '/streɪt/' },
  student: { tr: 'طالب', pos: 'noun', pr: '/ˈstjuːdənt/' },
  studying: { tr: 'يدرس / مذاكرة', pos: 'verb', pr: '/ˈstʌdiɪŋ/' },
  support: { tr: 'دعم فني', pos: 'noun', pr: '/səˈpɔːrt/' },
  sure: { tr: 'متأكد', pos: 'adjective', pr: '/ʃʊər/' },
  surprise: { tr: 'مفاجأة', pos: 'noun', pr: '/sərˈpraɪz/' },
  surprised: { tr: 'متفاجئ', pos: 'adjective', pr: '/sərˈpraɪzd/' },
  system: { tr: 'نظام', pos: 'noun', pr: '/ˈsɪstəm/' },
  taken: { tr: 'مشغول / مأخوذ', pos: 'adjective', pr: '/ˈteɪkən/' },
  taking: { tr: 'يأخذ', pos: 'verb', pr: '/ˈteɪkɪŋ/' },
  task: { tr: 'مهمة', pos: 'noun', pr: '/tæsk/' },
  technical: { tr: 'تقني', pos: 'adjective', pr: '/ˈtɛknɪkəl/' },
  television: { tr: 'تلفاز', pos: 'noun', pr: '/ˈtɛlɪvɪʒən/' },
  tell: { tr: 'يخبر', pos: 'verb', pr: '/tɛl/' },
  text: { tr: 'رسالة نصية / يراسل', pos: 'verb', pr: '/tɛkst/' },
  there: { tr: 'هناك', pos: 'adverb', pr: '/ðɛər/' },
  these: { tr: 'هؤلاء', pos: 'pronoun', pr: '/ðiːz/' },
  thing: { tr: 'شيء', pos: 'noun', pr: '/θɪŋ/' },
  think: { tr: 'يفكر / يعتقد', pos: 'verb', pr: '/θɪŋk/' },
  throat: { tr: 'حلق', pos: 'noun', pr: '/θroʊt/' },
  times: { tr: 'مرات', pos: 'noun', pr: '/taɪmz/' },
  took: { tr: 'أخذ', pos: 'verb', pr: '/tʊk/' },
  topic: { tr: 'موضوع', pos: 'noun', pr: '/ˈtɒpɪk/' },
  traffic: { tr: 'حركة المرور', pos: 'noun', pr: '/ˈtræfɪk/' },
  trip: { tr: 'رحلة', pos: 'noun', pr: '/trɪp/' },
  trust: { tr: 'يثق', pos: 'verb', pr: '/trʌst/' },
  truth: { tr: 'الحقيقة', pos: 'noun', pr: '/truːθ/' },
  try: { tr: 'يحاول / يجرّب', pos: 'verb', pr: '/traɪ/' },
  turn: { tr: 'ينعطف / دور', pos: 'verb', pr: '/tɜːrn/' },
  twenty: { tr: 'عشرون', pos: 'number', pr: '/ˈtwɛnti/' },
  under: { tr: 'تحت', pos: 'preposition', pr: '/ˈʌndər/' },
  update: { tr: 'تحديث', pos: 'noun', pr: '/ʌpˈdeɪt/' },
  updated: { tr: 'مُحدّث', pos: 'adjective', pr: '/ʌpˈdeɪtɪd/' },
  urgent: { tr: 'عاجل', pos: 'adjective', pr: '/ˈɜːrdʒənt/' },
  wait: { tr: 'ينتظر', pos: 'verb', pr: '/weɪt/' },
  walking: { tr: 'مشي', pos: 'noun', pr: '/ˈwɔːkɪŋ/' },
  way: { tr: 'طريق / طريقة', pos: 'noun', pr: '/weɪ/' },
  website: { tr: 'موقع إلكتروني', pos: 'noun', pr: '/ˈwɛbsaɪt/' },
  welcome: { tr: 'مرحبًا / على الرحب', pos: 'interjection', pr: '/ˈwɛlkəm/' },
  well: { tr: 'جيد / بخير', pos: 'adverb', pr: '/wɛl/' },
  which: { tr: 'أيّ', pos: 'pronoun', pr: '/wɪtʃ/' },
  why: { tr: 'لماذا', pos: 'question word', pr: '/waɪ/' },
  wi: { tr: 'واي (واي فاي)', pos: 'noun', pr: '/waɪ/' },
  within: { tr: 'خلال / في غضون', pos: 'preposition', pr: '/wɪˈðɪn/' },
  without: { tr: 'بدون', pos: 'preposition', pr: '/wɪˈðaʊt/' },
  working: { tr: 'يعمل', pos: 'verb', pr: '/ˈwɜːrkɪŋ/' },
  worried: { tr: 'قلق', pos: 'adjective', pr: '/ˈwʌrid/' },
  worry: { tr: 'يقلق', pos: 'verb', pr: '/ˈwʌri/' },
  would: { tr: 'سوف / يود', pos: 'verb', pr: '/wʊd/' },
  wrong: { tr: 'خاطئ', pos: 'adjective', pr: '/rɒŋ/' },
  years: { tr: 'سنوات', pos: 'noun', pr: '/jɪərz/' },
  yesterday: { tr: 'أمس', pos: 'adverb', pr: '/ˈjɛstərdeɪ/' },
  yet: { tr: 'حتى الآن', pos: 'adverb', pr: '/jɛt/' },
  yourself: { tr: 'نفسك', pos: 'pronoun', pr: '/jɔːrˈsɛlf/' }
};

function enrichSentences(sentences) {
  for (const s of sentences) {
    for (const w of s.words) {
      const lower = w.word.toLowerCase();
      if ((!w.translation || w.translation.trim() === '') && VOCAB_MAP[lower]) {
        w.translation = VOCAB_MAP[lower].tr;
        w.partOfSpeech = VOCAB_MAP[lower].pos;
        w.pronunciation = VOCAB_MAP[lower].pr;
      } else if (!w.translation || w.translation.trim() === '') {
        w.translation = 'كلمة إنجليزية';
        w.partOfSpeech = 'vocabulary';
        if (!w.pronunciation) w.pronunciation = `/${lower}/`;
      }
    }
  }
}

enrichSentences(a1Data);
enrichSentences(a2Data);

fs.writeFileSync(A1_PATH, JSON.stringify(a1Data, null, 2), 'utf8');
fs.writeFileSync(A2_PATH, JSON.stringify(a2Data, null, 2), 'utf8');
console.log('Enrichment complete!');
